### ISSUE TITLE
[BUG] MSFS Flight Logging

### ISSUE THREAD

**Issue by N95JPL** [JPLogistics/MSFS_C152#25]
**Current version:**
 - Current mod version: V0.8.3
 - Current MSFS version: 1.9.5.0

**Describe the bug**
MSFS not logging flights in internal system

**To Reproduce**
Fully shut down aircraft, logbook doesn't save entry

**Expected behaviour**
After Battery off, logbook should trigger?

**Screenshots**

**Additional context**
Initially reported [here](https://forums.flightsimulator.com/t/c152x-realism-mod/252690/380?u=n95jpl), I actually don't know where to begin with this one, Logbook has a magnitude of MSFS Internal issues
Did it trigger using original mod?
Can we find out if we can actually resolve this through mod or is it Asobo's issue?

**Comment by oliverpope03** [comment]
This to do with "avionics switch" thing @N95JPL ive had the log book trigger only once whilst using my saitek panel to turn off avionics. the logbook system as a whole is flawed ive only seen 3 or 4 times in the ammount ive flown.

**Comment by N95JPL** [comment]
Ahh thanks!
We really need to try and figure out a work-around for the Avionics Switch as a whole!
I will reference this bug in a specific "Avionics Switch" report!
