### ISSUE TITLE
Tranponder lighting

### ISSUE THREAD

**Issue by daveji** [JPLogistics/MSFS_C152#29]
I notice the fitted tranponder display is not lit........is this correct for this version ?  Its not easy to read in daylight, would be impossible at night !

**Comment by N95JPL** [comment]
Hello!
The Transponder display that is depicted in game doesn't actually light up, as far as I know!
I will double-check and update a comment here!
Thanks for reporting!

**Comment by daveji** [comment]
Hi again N95JPL
I think you may be right that this transponder is unlit.  When I flew C150 transponders were not legally required and were not fitted at all. However, these days a Mode C transponder is required for all GA aircraft to operate in controlled airspace, including airfield control Zones, even in VFR. I assume the C152 is still used as a trainer in UK Fliying Schools, so will have a Xponder fitted, which surely must be lit if the A/C is used to train a pilot for a Night Rating.
I think would be good to have such a device in the Sim AC if possible.

**Comment by N95JPL** [comment]
The installed Transponder is Mode C rated?
This particular gauge doesn't have backlighting in real life either, I imagine night-rated aircraft will have a different system installed, or, as only required when you need to change it for whatever reason, using the dome lights?

However, we are thinking about modernising some equipment (if possible)!
