### ISSUE TITLE
[BUG] Stall Behaviour

### ISSUE THREAD

**Issue by N95JPL** [JPLogistics/MSFS_C152#44]
**Current version:**
 - Current mod version: V0.9.2
 - Current MSFS version: V1.11.6.0

**Describe the bug**
• Stall behavior is a bit odd, the nose never really wants to drop once the airplane stalls, it just goes from flying to sinking with no nose drop or reaction from the airplane. IRL you get a sudden nose drop and then it steadies into a sinking attitude during the stall (as long as you force the stall by keeping the nose high). If you release the back pressure, it recovers easily by itself.  The actual airplane is quite reluctant to go into a spin, you have to give it a little help and fly it purposefully uncoordinated or kick the rudder.
Stall behavior changes with flaps and power setting too, it's always been difficult to model stall behavior in sims, I'd say that having the aeroplane to actually drop its nose would be enough for the moment

**To Reproduce**
...

**Expected behaviour**
...

**Screenshots**
N/A

**Additional context**
Reported by l3leu on Discord & Forum

**Comment by RetiredMan93231** [comment]
This issue will be affected greatly by my proposed changes to the aircraft Weight and Balance, and the proposed changes to the wing incidence and twist parameters.  I recommend testing it again after implementing the proposed changes.

**Comment by N95JPL** [comment]
Hello!
Yes they will hopefully improve how it handles a stall situation!
We are going to try it tonight!

Thanks,
Joshua!

**Comment by RetiredMan93231** [comment]
The -1.0 degree of wing twist in this aircraft is specifically designed to produce this behavior.  The root end of the wings is designed to stall first, while the outer wing and ailerons remain effective for controlling the aircraft.  the nose will drop due the loss of lift, but it will not automatically roll into a spin...

**Comment by N95JPL** [comment]
Stall behaviour is much nicer now, cheers!

**Comment by N95JPL** [comment]
This should be resolved as of V0.9.3 Beta 5

Pending closure, awaiting public release!
