### ISSUE TITLE
[BUG] Autopilot Engages?

### ISSUE THREAD

**Issue by N95JPL** [JPLogistics/MSFS_C152#48]
**Current version:**
 - Current mod version: ALL
 - Current MSFS version: 1.0.11.7

**Describe the bug**
Autopilot engages with keystroke

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
Autopilot should have 0 authority

**Screenshots**

**Additional context**

**Comment by RetiredMan93231** [comment]
I am unable to duplicate this bug...  I have joystick buttons assigned to autopilot on/off and they have no affect on this aircraft.

**Comment by N95JPL** [comment]
I didn't manage to replicate either, however I have now fully disabled Autopilot systems in this aircraft!

**Comment by N95JPL** [comment]
This should be resolved as of V0.9.3 Beta 5

Pending closure, awaiting public release!
