### ISSUE TITLE
Simulation starts with Parking Brake Off 

### ISSUE THREAD

**Issue by FS2020-USER-TESTER** [JPLogistics/MSFS_C152#56]
**Current version:**
 - Current mod version:  V0.9.7
 - Current MSFS version: V1.13.17.0

Simulation starts with Parking Brake off and plane immediately starts takeoff roll. Not able to perform checklist.
If the parking brake is quickly applied it does not hold the plane in place.

**To Reproduce**
1. Choose a airport and press FLY (not choose a gate).

**Expected behavior**
Optimal would be -  starts at runway end with engine running at idle and parking brake on.

**Comment by N95JPL** [comment]
Hello, this was actually introduced after feedback from other users who wanted to do a "quick" getaway!
Most people wanting to do the checklists will start on a stand?
You can, however, modify the behaviour for Runway starts yourself to suit your needs!
In the JPLogistics-c152 folder go to
/SimObjects/Airplanes/Asobo_C152/ 
In there find "runway.flt"
Open it using your favourite text editor, and there's a line about Parking Brake, set the variable to '1' and save, load or sim (or restart if already opened) and it'll load with the brake applied!

Thanks!
