### ISSUE TITLE
[BUG] ADF Panel out-of-order

### ISSUE THREAD

**Issue by Aesculab** [JPLogistics/MSFS_C152#57]
**Current version:**
 - Current mod version: [V0.9.7]
 - Current MSFS version: [1.13.17.0]

**Describe the bug**
ADF-Tuner display is blanc and shows no numbers on startup even if Tuner is tuned "ON" (or starting mid-flight/on runway)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start on Airfield KRMG, Position 6
2. Turn Battery on, Turn ADF-Knob "ON"
3. Look at ADF
4. No ADF-Numbers viewable

**Expected behaviour**
I'd like to see numbers :<

**Screenshots**
![grafik](https://user-images.githubusercontent.com/35341633/109998783-e122c380-7d11-11eb-9ee0-e6663d37c2b5.png)

**Additional context**
![grafik](https://user-images.githubusercontent.com/35341633/109999084-2646f580-7d12-11eb-8e72-377cf3d025df.png)
active mods

**Comment by N95JPL** [comment]
Hello!
Firstly thanks for reporting!
Our discord community made me aware of this too!
It will be fixed in the next release, for now though, there is a "quick-fix"
I'll paste the "Discord Announcement" I sent out to everybody below!

-- Discord Message --

```
@everyone … I have been made aware of an issue with the ADF, once again I am so sorry for this! But there is a simple fix for now!

Feeling brave?
Only joking, if you want you should be able to fix the ADF yourself before I release an update in the next week

Instructions;
Got to the your community files and open JPLogistics-c152/SimObjects/Airplanes/Asobo_C152/Panel
Open the Panel.xml file, find the line that reads “<SimVar name=“CIRCUIT ON:35” unit=“Boolean”/>” under the ADF part, Change the 35 to 10!

Under the HourMeter turn the 35 into 2!
And it _should_ work temporarily!
Restart MSFS and it’ll come alive!
```

I will get the next version ready for release as soon as I have worked out a few more issues!
Thanks!

**Comment by N95JPL** [comment]
Fixed, Closed!
