### ISSUE TITLE
[FEATURE] DME

### ISSUE THREAD

**Issue by NezHaut** [JPLogistics/MSFS_C152#6]
Hi !
First, a big thank you for this great work !
I'm just wondering if you could add a DME to the cockpit, so it become possible to fly most IFR approaches (appart GNSS ones), and fly IFR outside of the USA also.

Thanks again for your work.
Best regards !

Tim

**Comment by N95JPL** [comment]
Hello,
We have recently discussed this between the devs, we are planning to add a DME (Along with an updated Transponder) however, at present we need to wait for the SDK & Blender2MSFS Plugin to be fixed up!
But, rest assured it will come!

We are glad you like the mod! Please feel free to suggest more features & report any issues!

**Comment by ancrm114d** [comment]
Adding my support of wanting a DME is this aircraft. Thanks to all the devs for their great work.

**Comment by N95JPL** [comment]
Closing this issue for now, a "work-around" was released in V0.9.5 - this will remain on Dev Plan when SDK allows!

**Comment by therealplato** [comment]
Hello, I was super excited to find this mod, I like the 152 and its lack of a DME was painful. I would love to contribute how I can to the next iteration of the DME. I have neither experience with MSFS modding nod modeling but I have some JS experience.

So far I have been researching standalone DME equipment. From what I have found so far, BendixKing is the most common.
The panels that seem most likely are: [KDI-572](https://www.bendixking.com/en/products/nc/navigation-and-communication/kdi-572) and [KN-26a](https://www.bendixking.com/en/products/nc/navigation-and-communication/kn-62a):
![BK-KN-62A-946x946](https://user-images.githubusercontent.com/764725/124683097-4cd09500-de9a-11eb-8566-6c6788879266.jpg)

![BK-p-KDI573-detail-470x290](https://user-images.githubusercontent.com/764725/124683004-21e64100-de9a-11eb-8589-725c057734e1.jpg)

Other BendixKing displays are KDI-573 (a copilot's duplicate display) and KDI-574 (same as 572 but mode selection switch is mounted external to the panel.)

As a user I'd prefer the KDI-572 to avoid having to deal with yet more double knobs (the KN-62a actually has a "triple" knob - you pull it out to add 0.05, i.e. if you need to tune from 119.5 to 119.55.) Instead the 572 would be driven by existing NAV1 and NAV2 sources (with the caveat that switching to HLD "remembers" its most recent setting until switched back to N1/N2).

I found the pilot's guide for KN-26a and KDI-562; and the installation manual for the KDI-572, all attached: [bendixking-dme-manuals.zip](https://github.com/JPLogistics/JPLogistics_C152/files/6773486/bendixking-dme-manuals.zip). The IM has full specs including weight, panel dimensions, power draw, antenna diagrams.

What SDK limitations prevent moving forward with a standalone DME panel?
