### ISSUE TITLE
[FEATURE] Checklists

### ISSUE THREAD

**Issue by oliverpope03** [JPLogistics/MSFS_C152#7]
### Preflight Checks
TBA

### Normal Procedures
- [x] Before Starting Engine
- [x] Starting Engine
- [x] Run Up Before Takeoff (Engine Test)
- [ ] Normal Takeoff
- [ ] Short Field Takeoff
- [ ] Cruise
- [ ] Descent
- [ ] Normal Landing
- [ ] Short Field Landing
- [ ] After Landing
- [ ] Securing Aircraft
- [ ] UK(US)-Loc

### Emergency Procedures
TBA

### Reference
https://www.puc.edu/__data/assets/pdf_file/0004/9058/C152Checklist.pdf

**Comment by Ohmsquare16** [comment]
Maybe you could ask the guy over at steam guides who has already made a very good checklist for 152. See here: https://steamcommunity.com/sharedfiles/filedetails/?id=2208394249

**Comment by RetiredMan93231** [comment]
Section 4 of the 1978 C152 POH has detailed checklists that can be used to create the required additional in-game checklists...
[1978-Pilots-Operating-Handbook-Cessna-152.pdf](https://github.com/JPLogistics/MSFS_C152/files/5666093/1978-Pilots-Operating-Handbook-Cessna-152.pdf)

**Comment by RetiredMan93231** [comment]
Here are some additional C152 checklists...
[CESSNA 152 QRH_1.pdf](https://github.com/JPLogistics/MSFS_C152/files/5666110/CESSNA.152.QRH_1.pdf)

**Comment by N95JPL** [comment]
There are perfect, thanks!

**Comment by N95JPL** [comment]
Closing - moving to DEV Repo
